{% set name = "sqlalchemy-vertica-python" %}
{% set version = "0.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-vertica-python-{{ version }}.tar.gz
  sha256: 5cbebb9875e59366b9e3b4791ef7c2a8e45dbe460fd27687f3dc742dc058a024

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - vertica-python

test:
  imports:
    - sqla_vertica_python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluelabsio/sqlalchemy-vertica-python
  summary: Vertica dialect for sqlalchemy using vertica_python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
